export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import "../reset.css";

import "../globals.scss";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt">
      <body>{children}</body>
    </html>
  );
}
